version: 2
updates:
- package-ecosystem: npm
  directory: "/eslint-config"
  schedule:
    interval: daily
  versioning-strategy: increase
  groups:
    eslint-config-dependencies:
      patterns:
        - "*"
